### ISSUE TITLE
Create fork for english one on @afk0901

### ISSUE THREAD

**Issue by judyfong** [Einfaldlega-Hugmyndir/Compound_Interest_Calculator#12]
Also on this one the github pages link is wrong

**Comment by afk0901** [comment]
Solved, accessible again on the afk0901 [gh-page](https://afk0901.github.io/Compound_Interest_Calculator/) and also still accessible on this repo [gh-page](https://einfaldlega-hugmyndir.github.io/Compound_Interest_Calculator/) page but in Icelandic.

**Comment by judyfong** [comment]
Sorry i should have been more specific for einfaldlega hugmyndir's repo, in the readme, it points to the wrong gh pages

**Comment by afk0901** [comment]
Oh I'm sorry, that was my mistake. Fixed now.

**Comment by judyfong** [comment]
So it looks like maintaining both an icelandic and english one is proving a difficult challenge. If you look at samromur.is and their github you can see one way to separate out the language files and then show a different file (per fork [this part's new]).
